# Generated by Django 3.1.6 on 2021-02-03 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brgb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('green', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('blue', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='Hsl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hue', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(360)])),
                ('saturation', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('lightness', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Rgb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('green', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('blue', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
    ]
