# Generated by Django 3.1.6 on 2021-02-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgb',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='rgb',
            name='green',
        ),
        migrations.RemoveField(
            model_name='rgb',
            name='red',
        ),
    ]
