# Generated by Django 3.1.6 on 2021-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgb',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rgb',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rgb',
            name='red',
            field=models.IntegerField(default=0),
        ),
    ]
