# Generated by Django 3.1.6 on 2021-02-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210203_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSpecsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='brgb',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brgb',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brgb',
            name='red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hsl',
            name='hue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hsl',
            name='lightness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hsl',
            name='saturation',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ColorSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_type', models.CharField(choices=[('RGB', 'RGB'), ('HSL', 'HSL'), ('BRGB', 'BRGB')], default='RGB', max_length=4)),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
                ('hue', models.IntegerField(default=0)),
                ('saturation', models.IntegerField(default=0)),
                ('lightness', models.IntegerField(default=0)),
                ('brgb_red', models.IntegerField(default=0)),
                ('brgb_green', models.IntegerField(default=0)),
                ('brgb_blue', models.IntegerField(default=0)),
                ('color_specs_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colorspecscollection')),
            ],
        ),
    ]
