# Generated by Django 3.1.6 on 2021-02-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210206_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorspecs',
            name='blue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='brgb_blue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='brgb_green',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='brgb_red',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='color_specs_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.colorspecscollection'),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='green',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='hue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='lightness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='red',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorspecs',
            name='saturation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
