# Generated by Django 3.1.6 on 2021-02-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210207_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorspecs',
            name='color_specs_collection',
        ),
    ]
