# Generated by Django 3.1.6 on 2021-02-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_colorspecs_color_specs_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorspecs',
            name='color_specs_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.colorspecscollection'),
        ),
    ]
